version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tri_talent_db
    environment:
      POSTGRES_DB: tri_talent_db
      POSTGRES_USER: tri_user
      POSTGRES_PASSWORD: tri_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tri_user -d tri_talent_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
