# List of full TFRRS URLs to scrape (covering all provided seasons and divisions)
list_urls:
  - "https://www.tfrrs.org/lists/5018/2025_NCAA_Division_I_Outdoor_Qualifying_List"

# Scraper settings
scraping:
  # Delay between requests to avoid rate limiting (seconds)
  request_delay_seconds: 1.5
  # Maximum rows to parse per table (should match "top 500")
  max_athletes_per_page: 500
  timeout_seconds: 15

# CSS selectors for parsing
selectors:
  results_table: "table"
  result_rows: "tr"

# Time normalization rules
# (handled in code; included here for reference)
time_normalization:
  remove_non_numeric: "[^0-9.:]"
