# List of full TFRRS URLs to scrape (covering all provided seasons and divisions)
list_urls:
  - "https://www.tfrrs.org/lists/5018/2025_NCAA_Division_I_Outdoor_Qualifying_List"
  - "https://tf.tfrrs.org/lists/4867/2024_2025_NCAA_Division_I_Indoor_List_FINAL"
  - "https://www.tfrrs.org/lists/4515/2024_NCAA_Division_I_Rankings_FINAL"
  - "https://www.tfrrs.org/lists/4364/2023_2024_NCAA_Div_I_Indoor_Qualifying_FINAL"
  - "https://tfrrs.org/lists/4044/2023_NCAA_Division_I_All_Schools_Rankings"
  - "https://tfrrs.org/lists/3901/2022_2023_NCAA_Div_I_Indoor_Qualifying_FINAL"
  - "https://www.tfrrs.org/lists/3711/2022_NCAA_Division_I_Outdoor_Qualifying_FINAL"
  - "https://tfrrs.org/lists/3492/2021_2022_NCAA_Div_I_Indoor_Qualifying_FINAL"
  - "https://tfrrs.org/lists/3191/2021_NCAA_Division_I_Outdoor_Qualifying_FINAL"
  - "https://tfrrs.org/lists/3157/2020_2021_NCAA_Div_I_Indoor_Qualifying_FINAL"
  - "https://www.tfrrs.org/lists/2909/2020_NCAA_Division_I_Outdoor_Qualifying"
  - "https://m.tfrrs.org/lists/2770/2019_2020_NCAA_Div_I_Indoor_Qualifying_FINAL"
  - "https://m.tfrrs.org/lists/2568/2019_NCAA_Division_I_Outdoor_Qualifying_FINAL"
  - "https://tfrrs.org/lists/2324/2018_2019_NCAA_Div_I_Indoor_Qualifying_FINAL"

# Scraper settings
scraping:
  # Delay between requests to avoid rate limiting (seconds)
  request_delay_seconds: 1.5
  # Maximum rows to parse per table (should match "top 500")
  max_athletes_per_page: 500
  timeout_seconds: 15

# CSS selectors for parsing
selectors:
  results_table: "table"
  result_rows: "tr"

# Time normalization rules
# (handled in code; included here for reference)
time_normalization:
  remove_non_numeric: "[^0-9.:]"
